# coding: utf-8

"""
    Weheat Backend

    This is the backend for the Weheat project

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class DhwType(int, Enum):
    """
    DHW Type of the heat pump   - Unknown: Not known if DHW is available (0)   - DhwAvailable: DHW is available (1)   - DhwUnavailable: DHW is not available (2)
    """

    """
    allowed enum values
    """
    NUMBER_0 = 0
    NUMBER_1 = 1
    NUMBER_2 = 2

    @classmethod
    def from_json(cls, json_str: str) -> DhwType:
        """Create an instance of DhwType from a JSON string"""
        return DhwType(json.loads(json_str))


